language: ruby
sudo: false
rvm:
  - "2.3.1"
  - "2.3.3"
  - "2.4.1"


before_install: gem install bundler

script: bin/travis

matrix:
  fast_finish: true

env:
  matrix:
    - BUILD_TYPE=rspec
    - BUILD_TYPE=rubocop
